---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies that are not longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "make web directory"
  file:
    path: ~/web
    state: directory

- name: "install index page"
  copy:
    src: "files/index.js"
    dest: "~/web/index.js"
    

- name: "start web server"
  become : yes
  shell: |
    pm2 start ~/web/index.js -f
